# Generated by Django 4.1.2 on 2022-10-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.IntegerField()),
                ('loan_scheme', models.IntegerField(null=True)),
                ('loan_amount', models.IntegerField(null=True)),
                ('disbursment_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_no', models.IntegerField(null=True)),
                ('inst_no', models.IntegerField(null=True)),
                ('install_amount', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('due_date', models.DateField(null=True)),
            ],
        ),
    ]
