# Generated by Django 4.1.2 on 2022-10-27 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='loan_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan'),
        ),
    ]
