# Generated by Django 4.1.2 on 2022-10-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_shedule_loan_no'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loan',
            table='loan',
        ),
        migrations.AlterModelTable(
            name='shedule',
            table='shedule',
        ),
    ]
