# Generated by Django 4.1.2 on 2022-10-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_table_alter_shedule_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_no',
            field=models.IntegerField(unique=True),
        ),
    ]
