# Generated by Django 4.1.2 on 2022-11-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_shedule_install_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='install_amount',
            field=models.DecimalField(decimal_places=0, max_digits=11, null=True),
        ),
    ]
