# Generated by Django 4.1.2 on 2022-11-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='incr22',
            field=models.FloatField(null=True),
        ),
    ]
