# Generated by Django 4.1.2 on 2022-11-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_pensioner_incr22'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='incr22',
            field=models.FloatField(null=True),
        ),
    ]
