# Generated by Django 4.1.2 on 2022-11-07 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_payment_incr22'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=20, null=True)),
                ('bname', models.CharField(max_length=10)),
                ('bb', models.CharField(max_length=20)),
                ('acctno', models.CharField(max_length=20)),
                ('payment_ratio', models.FloatField(max_length=4)),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pms.pensioner')),
            ],
        ),
        migrations.RemoveField(
            model_name='bankfamily',
            name='pensioner',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankFamily',
        ),
    ]
