# Generated by Django 4.1.2 on 2022-11-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_status_ppo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='period_to',
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_on',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
