# Generated by Django 4.1.2 on 2022-11-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0009_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('acctno', 'month', 'year')},
        ),
        migrations.AddField(
            model_name='payment',
            name='bname',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
