# Generated by Django 4.1.2 on 2022-11-22 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_alter_status_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Increases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppo', models.CharField(max_length=9, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.CharField(max_length=10)),
                ('inc_amount', models.IntegerField(null=True)),
                ('tp_amount', models.IntegerField(null=True)),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.pensioner')),
            ],
            options={
                'verbose_name_plural': 'increases',
            },
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppo', models.CharField(max_length=9, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('p_type', models.CharField(max_length=1)),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.pensioner')),
            ],
        ),
    ]
