# Generated by Django 4.1.2 on 2022-11-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0012_increases_adjustment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='increases',
            unique_together={('ppo', 'description')},
        ),
    ]
