# Generated by Django 4.1.2 on 2022-11-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0013_alter_increases_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='increases',
            unique_together=set(),
        ),
    ]
