# Generated by Django 4.1.2 on 2022-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0014_alter_increases_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pensioner',
            name='fpname',
        ),
        migrations.AddField(
            model_name='pensioner',
            name='lpd',
            field=models.IntegerField(null=True),
        ),
    ]
