# Generated by Django 4.1.2 on 2022-12-05 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0016_increases_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pensioner',
            name='cpr',
            field=models.FloatField(null=True),
        ),
    ]
