# Generated by Django 4.1.2 on 2022-12-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0019_remove_payment_comm_amount_remove_payment_cp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppo', models.CharField(max_length=9, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(null=True)),
                ('p_type', models.CharField(max_length=1)),
                ('pensioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.pensioner')),
            ],
        ),
    ]
